version: '3'
services:
  resident_mapper_react_app_prod:
    container_name: resident_mapper_react_app_prod
    build:
      context: .
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN
    image: f4zphp27xi2s27yn/my_repo_topor:ra_events_react_app_prod
    volumes:
      - ${PWD}/.nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resident_mapper_react_app.rule=Host(`residentmapper.net`)"
      - "traefik.http.routers.resident_mapper_react_app.entrypoints=websecure"
      - "traefik.http.routers.resident_mapper_react_app.tls.certresolver=letsencrypt"
networks:
  default:
    external: true
    name: myNetwork
