version: '3'
services:
  resident_mapper_react_app_dev:
    container_name: resident_mapper_react_app_dev
    build:
      context: .
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN
    image: f4zphp27xi2s27yn/my_repo_topor:resident_mapper_react_app_dev
    volumes:
      - ${PWD}/.nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resident_mapper_react_app_dev.rule=Host(`dev-resident-mapper.libraryoftype.xyz`)"
      # - "traefik.http.routers.resident_mapper_react_app_dev.rule=Host(`xxx.residentmapper.net`)"
      # - "traefik.http.routers.resident_mapper_react_app_dev.entrypoints=websecure"
      # - "traefik.http.routers.resident_mapper_react_app_dev.tls.certresolver=letsencrypt"
networks:
  default:
    external: true
    name: myNetwork
