version: '3'
services:
  resident_mapper_react_app_prod:
    container_name: resident_mapper_react_app_prod
    build:
      context: .
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN
    image: f4zphp27xi2s27yn/my_repo_topor:resident_mapper_react_app_prod
    volumes:
      - ${PWD}/.nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resident_mapper_react_app_prod.rule=Host(`residentmapper.net`)"
      - "traefik.http.routers.resident_mapper_react_app_prod.entrypoints=websecure"
      - "traefik.http.routers.resident_mapper_react_app_prod.tls.certresolver=letsencrypt"
    environment:
      - REACT_APP_MAPBOX_ACCESS_TOKEN
networks:
  default:
    external: true
    name: myNetwork
