version: "3"
services:
  ra-mapper-react-app:
    container_name: resident_mapper_react_app_dev
    build:
      context: .
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN
    image: docker-registry.libraryoftype.xyz/ra-mapper-react-app:latest
    ports:
      - 80:80
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    name: myNetwork
    external: true
