version: "3"
services:
  resident_mapper_react_app_dev:
    container_name: resident_mapper_react_app_dev
    build:
      context: .
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN
    image: f4zphp27xi2s27yn/my_repo_topor:resident_mapper_react_app_dev
    ports:
      - 80:80
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    name: myNetwork
    external: true
