name: CI build-master

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check Mapbox Access Token
        run: echo ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
      - name: Create env file
        run: echo REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }} > .env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: f4zphp27xi2s27yn/my_repo_topor:resident_mapper_react_app_prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REACT_APP_MAPBOX_ACCESS_TOKEN=${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
